### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Chunlinx** [minsangkim142/Reading-Comprehension-without-RNNs#1]
Hi,
when i try to run your code ,I got an error:
Reducing Glove Matrix
100%|█████████████████████████████████████████████████| 442/442 [01:32<00:00,  4.79it/s]
100%|███████████████████████████████████████████████████| 48/48 [00:10<00:00,  4.43it/s]
Processing 91600 vocabs
Total number of lines: 91604
Reduced vocab size: 91604
Reading GloVe from: ./glove.840B.300d.txt
Processing line 91600
Reading GloVe from: ./glove.840B.300d.char.txt

Tokenizing training data.
100%|█████████████████████████████████████████████████| 442/442 [01:25<00:00,  5.19it/s]
Tokenizing dev data.
100%|███████████████████████████████████████████████████| 48/48 [00:10<00:00,  4.77it/s]
Tokenizing complete
Processing 91600 vocabsTraceback (most recent call last):
  File "process.py", line 377, in <module>
    main()
  File "process.py", line 371, in main
    load_glove(Params.glove_dir,"glove",vocab_size = Params.vocab_size)
  File "process.py", line 203, in load_glove
    assert 0
AssertionError
can you tell me why this happend?

**Comment by minsangkim142** [comment]
Hi @Chunlinx, thanks for raising this issue. It seems that the vocab size of your GloVe is not identical to the vocab specified in the parameters. Check [here](https://github.com/minsangkim142/Reading-Comprehension-without-RNNs/blob/7beb2b55f33d185ff957c09ff6400319864e3c8e/params.py#L47). I'll look into why this might be happening. 

In the meantime, for a quick fix just change [this line](https://github.com/minsangkim142/Reading-Comprehension-without-RNNs/blob/7beb2b55f33d185ff957c09ff6400319864e3c8e/params.py#L47) to be something slightly higher than 91604 (for example 91610).

**Comment by minsangkim142** [comment]
This shouldn't be a problem anymore as of 765eb7f02aea4465d7d1dc9fc99d89723ea35df1
